sudo: required

env:
  DOCKER_IMAGE=subhakarkotta/terraform-kubectl-helm-awscli
  DOCKER_TAG=0.12.6-v1.13.7-v2.13.1-1.16.214

services:
  - docker

script:
  - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` -t $DOCKER_IMAGE:$DOCKER_TAG .
  - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE:$DOCKER_TAG
  - docker push $DOCKER_IMAGE:latest
